# Numpy
```
pip install numpy
```
- Mathematical Calculations
- Numpy Array Creation
- Shape
- indexing
- data types: b,i,u,f,c,m,M,O,S,u,V (https://numpy.org/doc/1.25/reference/arrays.dtypes.html#arrays-dtypes)
- more creation methods: arange, linspace, ones, zeros, eye, diag
- random numbers: Numpy Random Module
    - rand: Random values in given shape
    - randn: Return samples from the Standard normal distribution
    - randint: Return random integer from low(inclusive) to high(exclusive)
    - random: Return random floats in [0.0,1.0)
    - choice: Generates a random sample from given 1D array
    - Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()
- reshape: -1 for unknown
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- and: &, or: |, not: ~ (Bitwise works same as logical in case of boolean Values)
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing

In [2]:
import numpy as np

In [38]:
l = [1,2,3,4,5]
l1 = [[1,2,3],[4,5]]
l3 = [[[1 for j in range(3)] for i in range(2)] for k in range(3)]
arr = np.array(l1,dtype = 'O')

In [40]:
print(arr,type(arr),arr.shape,arr.dtype)

[list([1, 2, 3]) list([4, 5])] <class 'numpy.ndarray'> (2,) object


In [21]:
arr[1,0,2] = 100

In [25]:
arr[1,:,1:] = [[10,20],[30,40]]

In [26]:
arr

array([[[10,  1,  1],
        [ 1,  1,  1]],

       [[ 1, 10, 20],
        [ 1, 30, 40]],

       [[ 1,  1,  1],
        [ 1,  1,  1]]])

In [27]:
arr.astype('float')

array([[[10.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1., 10., 20.],
        [ 1., 30., 40.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [29]:
arr.dtype

dtype('int32')

In [35]:
np.arange(1,20,3,dtype='i1')

array([ 1,  4,  7, 10, 13, 16, 19], dtype=int8)

In [42]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [46]:
np.ones((3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [48]:
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [52]:
np.random.rand(2,3,2)*10+10

array([[[14.09274513, 18.00643573],
        [11.09828377, 14.85883872],
        [19.80580235, 15.26021437]],

       [[19.50574278, 19.88212631],
        [10.4855898 , 17.90535774],
        [15.97604309, 17.59146853]]])

In [53]:
np.random.randint(10,20,(3,4))

array([[12, 10, 14, 19],
       [12, 15, 14, 13],
       [11, 16, 18, 19]])

In [55]:
np.random.choice(np.arange(1,100),size=(3,4))

array([[85, 51, 37, 26],
       [77, 12, 63, 55],
       [31, 56, 44, 60]])

In [62]:
a = np.arange(1,101)
np.random.shuffle(a)

In [63]:
a

array([ 71,  31,  72,  75,  65,  52,  89,  38,  85,  76,  51,  46,  62,
        82,  53,   7,  84,  29,  58,  33,  73,   2,  47,  42,   3,  45,
        97,  15,  55,  63,  77,  78,  83,  61,  30,  23,   9,  14,  37,
        27,  26,  49,  43,  25, 100,  39,  95,  11,  24,  91,  18,   6,
        44,  21,  64,   5,  79,  67,  10,  69,  32,  90,  86,  41,  13,
        19,  87,  66,  16,  22,  54,   4,   1,   8,  93,  99,  68,  74,
        12,  81,  60,  17,  98,  35,  28,  36,  88,  57,  70,  59,  56,
        80,  48,  40,  92,  94,  20,  96,  50,  34])

In [72]:
a = a.reshape((5,4,5))

In [80]:
b = a[1,:2,:3].copy()

In [81]:
b[0,0] = 10

In [82]:
b

array([[10,  2, 47],
       [45, 97, 15]])

In [83]:
a

array([[[ 71,  31,  72,  75,  65],
        [ 52,  89,  38,  85,  76],
        [ 51,  46,  62,  82,  53],
        [  7,  84,  29,  58,  33]],

       [[  1,   2,  47,  42,   3],
        [ 45,  97,  15,  55,  63],
        [ 77,  78,  83,  61,  30],
        [ 23,   9,  14,  37,  27]],

       [[ 26,  49,  43,  25, 100],
        [ 39,  95,  11,  24,  91],
        [ 18,   6,  44,  21,  64],
        [  5,  79,  67,  10,  69]],

       [[ 32,  90,  86,  41,  13],
        [ 19,  87,  66,  16,  22],
        [ 54,   4,   1,   8,  93],
        [ 99,  68,  74,  12,  81]],

       [[ 60,  17,  98,  35,  28],
        [ 36,  88,  57,  70,  59],
        [ 56,  80,  48,  40,  92],
        [ 94,  20,  96,  50,  34]]])

In [84]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,20,30],[40,50,60]])

In [91]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [90]:
a-b

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [92]:
a+10

array([[11, 12, 13],
       [14, 15, 16]])

In [93]:
x = np.array([1,2,3,4,5,6,7,8,9,10])

In [94]:
y = 2*x+3

In [95]:
y

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [97]:
x[[1,3,5,4,7]]

array([2, 4, 6, 5, 8])

In [98]:
x[[True,False,False,False,True,True,False,False,True,False]]

array([1, 5, 6, 9])

In [100]:
x[x <= 4]

array([1, 2, 3, 4])

# Pandas 
```
pip install pandas 
pip install --upgrade pandas
```
- Pandas Series
- Pandas DataFrame --> use various ways to initialize it(dtype,columns,index)
- shape
- head
- tail
- convert to numpy array --> values
- columns
- to_csv (index = false)
- read_csv
-  drop(columns=[])
-  describe()
-  info()
-  iloc
-  loc
-  Access Particular Columns
-  indexing and slicing --> multirow and col
-  columns.get_loc
-  Fancy indexing
-  Filtering

In [101]:
import pandas as pd

In [105]:
l = [10,20,30,40,50]
ds = pd.Series(l,index=['A','B','C','D','E'],name='ABCDE')

In [106]:
ds

A    10
B    20
C    30
D    40
E    50
Name: ABCDE, dtype: int64

In [107]:
ds['A']

10

In [108]:
d = {
    'Phy':[97,89,65,75,80],
    'Maths':[87,99,85,95,100],
    'Chem':[95,69,57,85,90]}

In [109]:
d

{'Phy': [97, 89, 65, 75, 80],
 'Maths': [87, 99, 85, 95, 100],
 'Chem': [95, 69, 57, 85, 90]}

In [115]:
df = pd.DataFrame(d,index=['Tanu','Prag','Gaur','Swe','Aman'])

In [116]:
df

Phy  Maths  Chem
Tanu   97     87    95
Prag   89     99    69
Gaur   65     85    57
Swe    75     95    85
Aman   80    100    90

In [121]:
df[['Phy','Maths']]

Phy  Maths
Tanu   97     87
Prag   89     99
Gaur   65     85
Swe    75     95
Aman   80    100

In [122]:
df.shape

(5, 3)

In [124]:
df.head(n=2)

Phy  Maths  Chem
Tanu   97     87    95
Prag   89     99    69

In [125]:
df.tail(n=2)

Phy  Maths  Chem
Swe    75     95    85
Aman   80    100    90

In [126]:
df.values

array([[ 97,  87,  95],
       [ 89,  99,  69],
       [ 65,  85,  57],
       [ 75,  95,  85],
       [ 80, 100,  90]], dtype=int64)

In [127]:
df.to_numpy()

array([[ 97,  87,  95],
       [ 89,  99,  69],
       [ 65,  85,  57],
       [ 75,  95,  85],
       [ 80, 100,  90]], dtype=int64)

In [128]:
df.columns

Index(['Phy', 'Maths', 'Chem'], dtype='object')

In [129]:
df.to_csv('Marks.csv',)

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Tanu to Aman
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Phy     5 non-null      int64
 1   Maths   5 non-null      int64
 2   Chem    5 non-null      int64
dtypes: int64(3)
memory usage: 332.0+ bytes


In [131]:
df.describe()

Phy       Maths      Chem
count   5.000000    5.000000   5.00000
mean   81.200000   93.200000  79.20000
std    12.377399    6.870226  15.78607
min    65.000000   85.000000  57.00000
25%    75.000000   87.000000  69.00000
50%    80.000000   95.000000  85.00000
75%    89.000000   99.000000  90.00000
max    97.000000  100.000000  95.00000

In [132]:
data = pd.read_csv('Fl1.csv')

In [133]:
data

A   B   C     D
0  1   2   3   4.0
1  5   6   7   8.0
2  9  10  11  12.0
3  3   2   1   NaN

In [138]:
df.iloc[0:3,::2]

Phy  Chem
Tanu   97    95
Prag   89    69
Gaur   65    57

In [141]:
df.loc['Tanu','Phy']

97

In [142]:
df['Phy']

Tanu    97
Prag    89
Gaur    65
Swe     75
Aman    80
Name: Phy, dtype: int64

In [143]:
df.loc[['Prag','Swe'],['Phy','Chem']]

Phy  Chem
Prag   89    69
Swe    75    85

In [144]:
df

Phy  Maths  Chem
Tanu   97     87    95
Prag   89     99    69
Gaur   65     85    57
Swe    75     95    85
Aman   80    100    90

In [145]:
df+10

Phy  Maths  Chem
Tanu  107     97   105
Prag   99    109    79
Gaur   75     95    67
Swe    85    105    95
Aman   90    110   100

In [156]:
df[df['Phy'] >= 80][['Phy','Chem']]

Phy  Chem
Tanu   97    95
Prag   89    69
Aman   80    90

In [149]:
df

Phy  Maths  Chem
Tanu   97     87    95
Prag   89     99    69
Gaur   65     85    57
Swe    75     95    85
Aman   80    100    90

In [151]:
df.drop(columns=['Chem'],index = ['Gaur'])

Phy  Maths
Tanu   97     87
Prag   89     99
Swe    75     95
Aman   80    100

In [152]:
import matplotlib

In [153]:
import seaborn